package cn.dyan.domain;

public class UserMenu {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_menu.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_menu.menu_id
     *
     * @mbg.generated
     */
    private String menuId;

    public UserMenu(String userid,String menuId){
        this.userId = userid;
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_menu.user_id
     *
     * @return the value of tb_user_menu.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_menu.user_id
     *
     * @param userId the value for tb_user_menu.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_menu.menu_id
     *
     * @return the value of tb_user_menu.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_menu.menu_id
     *
     * @param menuId the value for tb_user_menu.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
}