package cn.dyan.mapping;

import cn.dyan.domain.Email;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_email",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_email (id, seller, ",
        "subject, created)",
        "values (#{id,jdbcType=BIGINT}, #{seller,jdbcType=VARCHAR}, ",
        "#{subject,jdbcType=VARCHAR}, #{created,jdbcType=DATE})"
    })
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, subject, created",
        "from tb_email",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    Email selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, subject, created",
        "from tb_email"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="subject", property="subject", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    List<Email> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_email
     *
     * @mbg.generated
     */
    @Update({
        "update tb_email",
        "set seller = #{seller,jdbcType=VARCHAR},",
          "subject = #{subject,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=DATE}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Email record);
}