package cn.dyan.mapping;

import cn.dyan.domain.OrderLog;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface OrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_log
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_order_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_log
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_order_log (id, seller, ",
        "buyer, created)",
        "values (#{id,jdbcType=BIGINT}, #{seller,jdbcType=VARCHAR}, ",
        "#{buyer,jdbcType=VARCHAR}, #{created,jdbcType=DATE})"
    })
    int insert(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_log
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, buyer, created",
        "from tb_order_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="buyer", property="buyer", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    OrderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_log
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, buyer, created",
        "from tb_order_log"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="buyer", property="buyer", jdbcType=JdbcType.VARCHAR),
        @Result(column="created", property="created", jdbcType=JdbcType.DATE)
    })
    List<OrderLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order_log
     *
     * @mbg.generated
     */
    @Update({
        "update tb_order_log",
        "set seller = #{seller,jdbcType=VARCHAR},",
          "buyer = #{buyer,jdbcType=VARCHAR},",
          "created = #{created,jdbcType=DATE}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderLog record);
}