package cn.dyan.mapping;

import cn.dyan.domain.Order;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_order (id, seller, ",
        "buyer, amount, status, ",
        "created)",
        "values (#{id,jdbcType=BIGINT}, #{seller,jdbcType=VARCHAR}, ",
        "#{buyer,jdbcType=VARCHAR}, #{amount,jdbcType=REAL}, #{status,jdbcType=BIT}, ",
        "#{created,jdbcType=TIMESTAMP})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, buyer, amount, status, created",
        "from tb_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="buyer", property="buyer", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.REAL),
        @Result(column="status", property="status", jdbcType=JdbcType.BIT),
        @Result(column="created", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, seller, buyer, amount, status, created",
        "from tb_order"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="seller", property="seller", jdbcType=JdbcType.VARCHAR),
        @Result(column="buyer", property="buyer", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.REAL),
        @Result(column="status", property="status", jdbcType=JdbcType.BIT),
        @Result(column="created", property="created", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_order
     *
     * @mbg.generated
     */
    @Update({
        "update tb_order",
        "set seller = #{seller,jdbcType=VARCHAR},",
          "buyer = #{buyer,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=REAL},",
          "status = #{status,jdbcType=BIT},",
          "created = #{created,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Order record);
}