package cn.dyan.mapping;

import cn.dyan.domain.UserMenu;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_menu
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_user_menu",
        "where user_id = #{userId,jdbcType=VARCHAR}",
          "and menu_id = #{menuId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("userId") String userId, @Param("menuId") String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_menu
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_user_menu (user_id, menu_id)",
        "values (#{userId,jdbcType=VARCHAR}, #{menuId,jdbcType=VARCHAR})"
    })
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_menu
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "user_id, menu_id",
        "from tb_user_menu"
    })
    @Results({
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="menu_id", property="menuId", jdbcType=JdbcType.VARCHAR, id=true)
    })
    List<UserMenu> selectAll();
}